version: '{build}'
branches:
  only: [master]
init:
- ps: Install-Product node 8
install:
- cmd: npm -v 
- cmd: node -v 
- cmd: npm install -g yarn
- cmd: yarn
cache:
- node_modules
build: off
test_script:
- cmd: yarn test
